### ISSUE TITLE
Why is disable_performance_standby = true in the default config? 

### ISSUE THREAD

**Issue by kaparora** [hashicorp/terraform-aws-vault-ent-starter#12]
Hi Please can you tell me why disable_performance_standby = true is set by default for the deployment?

**Comment by hashicorp-peter** [comment]
[disable_performance_standby = true](https://github.com/hashicorp/terraform-aws-vault-ent-starter/blob/main/modules/user_data/templates/install_vault.sh.tpl#L42)

**Comment by Omar-Khawaja** [comment]
Thanks for bringing this issue up! Linking a #15 to this for the fix.
